# Generated by Django 4.0.2 on 2022-02-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='qusntity',
            new_name='quantity',
        ),
    ]
