# Generated by Django 4.0.2 on 2022-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_qusntity_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], default='pending', max_length=10),
        ),
    ]
