# Generated by Django 4.0.2 on 2022-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('delivered', 'DELIVERED'), ('delivered', 'CANCELED')], default='pending', max_length=10),
        ),
    ]
